"""新增调查档案管理系统

Revision ID: add_site_survey_system
Revises: 
Create Date: 2025-11-06 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_site_survey_system'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建 site_surveys 表
    op.create_table('site_surveys',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('site_id', sa.Integer(), nullable=False),
        sa.Column('survey_date', sa.DateTime(), nullable=False),
        sa.Column('surveyor_name', sa.String(length=100), nullable=False),
        sa.Column('surveyor_phone', sa.String(length=30), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('gps_accuracy', sa.Float(), nullable=True),
        sa.Column('site_type', sa.String(length=50), nullable=True),
        sa.Column('tower_type', sa.String(length=50), nullable=True),
        sa.Column('available_height_m', sa.Float(), nullable=True),
        sa.Column('load_capacity_kg', sa.Float(), nullable=True),
        sa.Column('power_available', sa.Boolean(), nullable=True),
        sa.Column('power_distance_m', sa.Float(), nullable=True),
        sa.Column('power_capacity_kw', sa.Float(), nullable=True),
        sa.Column('earthing_feasible', sa.Boolean(), nullable=True),
        sa.Column('fiber_available', sa.Boolean(), nullable=True),
        sa.Column('fiber_distance_m', sa.Float(), nullable=True),
        sa.Column('duct_notes', sa.Text(), nullable=True),
        sa.Column('microwave_los', sa.Boolean(), nullable=True),
        sa.Column('los_azimuth_deg', sa.Float(), nullable=True),
        sa.Column('los_distance_km', sa.Float(), nullable=True),
        sa.Column('sensitive_points', sa.Text(), nullable=True),
        sa.Column('safety_notes', sa.Text(), nullable=True),
        sa.Column('permits_constraints', sa.Text(), nullable=True),
        sa.Column('owner_name', sa.String(length=100), nullable=True),
        sa.Column('owner_phone', sa.String(length=30), nullable=True),
        sa.Column('access_time_window', sa.String(length=100), nullable=True),
        sa.Column('entry_constraints', sa.Text(), nullable=True),
        sa.Column('feasibility', sa.String(length=30), nullable=True),
        sa.Column('risks', sa.Text(), nullable=True),
        sa.Column('recommendations', sa.Text(), nullable=True),
        sa.Column('extra_data', sa.JSON(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('work_order_id', sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
        sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_surveys_site_id'), 'site_surveys', ['site_id'], unique=False)
    
    # 创建 site_survey_photos 表
    op.create_table('site_survey_photos',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('survey_id', sa.String(length=32), nullable=False),
        sa.Column('original_name', sa.String(length=255), nullable=True),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('mime_type', sa.String(length=100), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.Column('exif', sa.JSON(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('gps_accuracy', sa.Float(), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('taken_at', sa.DateTime(), nullable=True),
        sa.Column('has_watermark', sa.Boolean(), nullable=True),
        sa.Column('watermark_data', sa.JSON(), nullable=True),
        sa.Column('hash_value', sa.String(length=64), nullable=True),
        sa.Column('uploaded_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['survey_id'], ['site_surveys.id'], ),
        sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_survey_photos_survey_id'), 'site_survey_photos', ['survey_id'], unique=False)
    
    # 创建 site_survey_archives 表
    op.create_table('site_survey_archives',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('site_id', sa.Integer(), nullable=False),
        sa.Column('work_order_id', sa.String(length=32), nullable=False),
        sa.Column('inspection_id', sa.String(length=32), nullable=False),
        sa.Column('template_id', sa.String(length=32), nullable=False),
        sa.Column('template_version', sa.String(length=20), nullable=True),
        sa.Column('current_version', sa.Integer(), nullable=True),
        sa.Column('content', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['inspection_id'], ['site_inspections.id'], ),
        sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
        sa.ForeignKeyConstraint(['template_id'], ['inspection_templates.id'], ),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_survey_archives_archive_id'), 'site_survey_archives', ['id'], unique=False)
    op.create_index(op.f('ix_site_survey_archives_inspection_id'), 'site_survey_archives', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_site_survey_archives_site_id'), 'site_survey_archives', ['site_id'], unique=False)
    op.create_index(op.f('ix_site_survey_archives_template_id'), 'site_survey_archives', ['template_id'], unique=False)
    op.create_index(op.f('ix_site_survey_archives_work_order_id'), 'site_survey_archives', ['work_order_id'], unique=False)
    
    # 创建 site_survey_archive_versions 表
    op.create_table('site_survey_archive_versions',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('archive_id', sa.String(length=32), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('content', sa.JSON(), nullable=False),
        sa.Column('diff', sa.JSON(), nullable=True),
        sa.Column('change_summary', sa.Text(), nullable=True),
        sa.Column('changed_by', sa.Integer(), nullable=True),
        sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['archive_id'], ['site_survey_archives.id'], ),
        sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_survey_archive_versions_archive_id'), 'site_survey_archive_versions', ['archive_id'], unique=False)
    op.create_index(op.f('ix_site_survey_archive_versions_version'), 'site_survey_archive_versions', ['version'], unique=False)
    
    # 创建 site_survey_archive_kv_index 表
    op.create_table('site_survey_archive_kv_index',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('archive_id', sa.String(length=32), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('path', sa.String(length=200), nullable=False),
        sa.Column('field_label', sa.String(length=200), nullable=True),
        sa.Column('type', sa.String(length=20), nullable=True),
        sa.Column('value_number', sa.Float(), nullable=True),
        sa.Column('value_bool', sa.Boolean(), nullable=True),
        sa.Column('value_string', sa.Text(), nullable=True),
        sa.Column('value_datetime', sa.DateTime(), nullable=True),
        sa.Column('raw_json', sa.JSON(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['archive_id'], ['site_survey_archives.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_survey_archive_kv_index_archive_id'), 'site_survey_archive_kv_index', ['archive_id'], unique=False)
    op.create_index(op.f('ix_site_survey_archive_kv_index_path'), 'site_survey_archive_kv_index', ['path'], unique=False)
    op.create_index(op.f('ix_site_survey_archive_kv_index_updated_at'), 'site_survey_archive_kv_index', ['updated_at'], unique=False)
    op.create_index(op.f('ix_site_survey_archive_kv_index_version'), 'site_survey_archive_kv_index', ['version'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_survey_archive_kv_index')
    op.drop_table('site_survey_archive_versions')
    op.drop_table('site_survey_archives')
    op.drop_table('site_survey_photos')
    op.drop_table('site_surveys')
    # ### end Alembic commands ###
